[package]
name    = "free_term"
version = "0.1.0"
authors = ["Perrin Smith <perrinjamessmith@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "9.0.0"
os_pipe   = "0.9.2"
yaml-rust = "0.4"
